#!/usr/bin/python
URL_FILE="../url.properties"
DOWNLOAD_PATH="../downloads"
API_KEY="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
BASE_LOCATION="http://xxxxx:xxxx/api"
DCAT_NAMESPACE = "http://www.w3.org/ns/dcat#"
DCT_NAMESPACE = "http://purl.org/dc/terms/"
RDFS_NAMESPACE = "http://www.w3.org/2000/01/rdf-schema#"
FOAF_NAMESPACE = "http://xmlns.com/foaf/0.1/"
RDF_NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
